name: convoluted_build_check
on:
  push:
    branches:
      - main
      - stable

jobs:
  try_build:
    # Test structure requires files specific to this project, how to generalize?
    uses: Olgittmar/GithubWorkflow/.github/workflows/build_check_ubuntu.yml@main
